# Generated by Django 3.2.1 on 2021-05-05 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpack',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizpack',
            name='registered_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
