# Generated by Django 3.2.1 on 2021-05-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210505_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order_in_pack',
            field=models.IntegerField(null=True),
        ),
    ]
