# Generated by Django 3.2.1 on 2021-05-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_order_in_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order_in_pack',
        ),
    ]
