# Generated by Django 3.2 on 2021-05-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_delete_classmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.CharField(max_length=20)),
                ('beginDate', models.DateTimeField(auto_now_add=True)),
                ('manageTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.quser')),
            ],
        ),
    ]
