# Generated by Django 3.2 on 2021-05-05 03:42

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='className',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
