# Generated by Django 3.0.5 on 2021-05-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='quser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='quser',
            name='profile_pic',
        ),
    ]
