# Generated by Django 3.2 on 2021-05-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210504_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('beginDate', models.DateTimeField(auto_now_add=True)),
                ('manageTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.quser')),
            ],
        ),
    ]
