# Generated by Django 3.2 on 2021-05-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210504_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.CharField(max_length=20)),
                ('manageTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.quser')),
            ],
        ),
    ]
