# Generated by Django 3.2 on 2021-05-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_classmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassModel',
        ),
    ]
